vich_uploader:
    db_driver: orm

    mappings:
        personnel_image:
            uri_prefix: /images/personnels
            upload_destination: '%kernel.project_dir%/public/images/personnels'


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
